### ISSUE TITLE
Guidelines for Projects and Involvement

### ISSUE THREAD

**Issue by cookiengineer** [JSFoundation/js.foundation#18]
The JS Foundation sounds pretty awesome and I believe that the JS community needs a foundation to further unite ideas and progress in a sustainable manner. I also believe that the node.js foundation heavily benefited the node.js ecosystem and I see the JS foundation as a meta organization to unite different efforts of R&D projects and libraries to combine their ideas and more efficiently reuse existing resources.

However, it is currently unclear on how people can take part in the foundation, engage in the community or how they can join with their projects. What is the further goal of the JS foundation? Replacing/Involving in TC39 and ES-discuss or is it project-focussed to share resources?

Is this repository meant to exist so that people can pull-request their projects in? What are the necessary requirements for projects to take part in the JS foundation?

Our project is a bit divided from the existing JS ecosystem, in particular it's [lychee.js](https://github.com/Artificial-Engineering/lycheejs) and it is a self-improving peer-to-peer artificial intelligence that learns how to build software in a sustainable, decentralized manner. As many parts focus on sustainability and automation, many things had to be done completely differently (e.g. the cross-platform automated build toolchain to have binaries) than say, in the node-gyp or grunt world where most of the parts focus on manual flexibility through code rather than automation through convention.

~Cheers from Germany

**Comment by kborchers** [comment]
These are great questions and I will do my best to address them with the information we have right now.

> What is the further goal of the JS foundation? Replacing/Involving in TC39 and ES-discuss or is it project-focussed to share resources?

We are working to create a focal point for community and collaboration in the open source ecosystem in order to support and promote long-term sustainability for those projects. We will also be working to improve and drive standards, as we have for quite some time, through representation in TC39, W3C, etc as well as through new efforts we are supporting like chapters.io

> Is this repository meant to exist so that people can pull-request their projects in?

No, this repository is just meant to maintain the website and projects are added here once they are accepted into the JS Foundation.

> What are the necessary requirements for projects to take part in the JS foundation?

This is still a work in progress but if you look at https://github.com/JSFoundation/TAC/ you will see the documentation and policies being pulled together for the technical governance of the Foundation. Within the project life-cycle document in that repo, you will also find an application process which explains how to have your project considered. Please do keep in mind though, as we are still finalizing many of these policies and procedures, there may be significant delays in responding to applications.

I hope that helps!
