### ISSUE TITLE
UX: No easy way to get from CLA page to cla.js.foundation portal for project

### ISSUE THREAD

**Issue by platinumazure** [JSFoundation/js.foundation#26]
I just worked with a user who was conscientious and diligent enough to want to sign my project's CLA before opening a pull request, but he couldn't figure out how from the JS Foundation website. I did explain that the CLA only needs to be signed before merge, but as I explored this myself, I realized that there's a potential UX gap here where there's no easy way to start at the JS Foundation website and end up at the CLA signing portal for a project.

Here's what I propose (but feel free to bikeshed): We add a form to the bottom of http://js.foundation/CLA with a dropdown list of all projects and a Go button. Picking a project and clicking Go will open a new window pointing to a project's CLA portal (e.g., https://cla.js.foundation/qunitjs/qunit). This allows the user to navigate from js.foundation to a project's CLA portal easily, providing an alternative to just requiring that a PR be opened and the CLA bot come in and provide the project CLA portal link.

If this sounds acceptable, I'm happy to work on a PR if need be.

**Comment by kborchers** [comment]
I really like this idea. If you want to start a PR that would be great and I would be happy to review and provide additional feedback there. If you have questions feel free to use this issue. Thanks!

**Comment by platinumazure** [comment]
Hi @kborchers, I've been informed that the CLA should be good for all projects (e.g., if I sign the CLA v4.1 for ESLint, it should also be good for contributions I make afterward to QUnit).

If that's the case, then the per-project access I had outlined above is actually fairly useless. A user could just click a link to https://cla.js.foundation and just sign the CLA from there.

Am I correct that the CLA (current version) only needs to be signed once, in order to provide license for contributing to multiple projects? Or does each project require an individual signature?

**Comment by kborchers** [comment]
Our current system is GitHub org based. Though legally it is correct that one signature would work across all projects, our system only works on a repo or org basis so to implement this form it would need to reference at least one org/repo combo for each org link.

**Comment by platinumazure** [comment]
@kborchers Are there any plans to try to revamp the CLA assistant to handle one signature instead of per-organization? If that's desired or in the works, then I'd like to close this until that happens, to avoid too much wasted work.

**Comment by kborchers** [comment]
It probably would not be too hard to add that feature to our fork but I imagine it would not be accepted upstream since the original purpose of CLA Assistant was a hosted solution for individual projects to use alongside a number of other unrelated projects. Unfortunately, this is not something I have the time to do myself nor the resources to pay to have added at this time. If this is something you or someone else is interested in adding I would definitely agree that we should do that instead of creating this form but it is definitely not in progress right now.

**Comment by kborchers** [comment]
@platinumazure Is this something you are still interested in pursuing (either proper linking or edits to CLA Assistant to handle cross-org signatures)? I'd be happy to chat some time soon to figure out a plan to move forward if you or others are interested in trying to tackle this.

**Comment by platinumazure** [comment]
@kborchers I'm no longer sure whether there's anything we can/should do here. Probably best to close, unless you think this is something that we should pursue.

**Comment by kborchers** [comment]
@platinumazure I guess where I'm at on this is that the system "works" but could be better. I unfortunately don't have the time to dig into improving it but if it's something that interests you, I'd be happy to set up a test environment and give you free reign to play with it and see what you can come up with. Otherwise, I am also happy to just close it.

**Comment by platinumazure** [comment]
Thanks @kborchers, I'm in the same place you are, and I also don't have time to dig in anymore. I'll go ahead and close. Thanks very much for following up.
