### ISSUE TITLE
Template variables in the CLA assistant text.

### ISSUE THREAD

**Issue by sompylasar** [JSFoundation/js.foundation#27]
```
with the [JS Foundation IP Policy]({{ site.url }}{{ site.baseurl }}/pdf/ip-policy.pdf).
```

Example URL: https://cla.js.foundation/webpack/webpack.js.org

<img width="1097" alt="screen shot 2017-04-16 at 9 17 09 pm" src="https://cloud.githubusercontent.com/assets/498274/25078674/1b8dd6f8-22ea-11e7-9c6d-a140c2fb6f27.png">

**Comment by kborchers** [comment]
Thank you very much for reporting this issue. We are looking into the best way to fix this as a change to the CLA, by default, invalidates current CLA signatures and requires new signatures. In general, this is a good thing but since this is just a typographical error and not a substantive change, we are looking into how to make this change without requiring new CLA signatures and will fix it ASAP.

**Comment by kborchers** [comment]
This issue has finally been corrected. Thank you!
